name: Deploy Portfolio-front

on:
  push:
    branches:
      - main

jobs:
  clear-docker-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear docker context
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop portfolio-front || true
            docker system prune -a -f

  deploy-landing-page-dev:
    runs-on: ubuntu-latest
    needs: clear-docker-context
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: .
          target: portfolio-front

      - name: Build API Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /${{ secrets.SERVER_USERNAME }}/portfolio-front
            docker build -f Dockerfile -t portfolio-front .

      - name: Mount Landing page Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker run -d \
            --name=u-cms-landing-dev \
            -e NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" \
            -p 3000:3000 \
            --restart always \
            portfolio-front